-- ============================================================
-- 075_add_employee_iqama_tracking.sql
--
-- Iqama (Saudi residency permit) expiry tracking for foreign
-- employees, with expiry notifications for HR/admin users.
--
-- SCOPED HONESTLY: this system has no background cron scheduler
-- (a disclosed, pre-existing limitation — see the recurring
-- invoice feature's "generate due now" for the same pattern).
-- Notifications are generated by an ON-DEMAND check
-- (EmployeeDocumentsService.checkExpiringIqamas()), triggered
-- either by a person clicking "Check Now" in the UI, or by an
-- external scheduler (e.g. the hosting platform's own cron) hitting
-- the same endpoint on a schedule — this migration and the service
-- built on it do not make that scheduling happen by themselves.
--
-- nationality/iqama_number/iqama_expiry_date are added directly to
-- employees, not a separate "documents" table — scoped to exactly
-- what was asked for (Iqama expiry), not a general document-
-- management system covering passports, work permits, etc.
-- ============================================================

ALTER TABLE employees ADD COLUMN nationality VARCHAR(100);
ALTER TABLE employees ADD COLUMN iqama_number VARCHAR(50);
ALTER TABLE employees ADD COLUMN iqama_expiry_date DATE;
